id: PBC0C990E
initial_creation_type: ocr
source_metadata:
  volumes:
    63cefccd5ba14133862c54d8a21d659c:
      base_file: v047.txt
      image_group_id: I1PD95892
      title: རོ་བསྲེག་པའི་ཆོ་ག།
      total_pages: 1464
      volume_number: 47
